CREATE TABLE messages (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          recipient VARCHAR(100) NOT NULL,
                          text VARCHAR(10000) NOT NULL,
                          created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                          PRIMARY KEY (id)
);