CREATE TABLE audit_log (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           event_type VARCHAR(100) NOT NULL,
                           message VARCHAR(10017),                          -- подумай какая длина
    created_at TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id)
);